name: whatfix_flutter_webview
description: A Flutter plugin that provides a WebView widget on Android and iOS.
repository: https://github.com/flutter/plugins/tree/main/packages/webview_flutter/webview_flutter
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 3.0.4

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: whatfix_flutter_webview_android
      ios:
        default_package: whatfix_flutter_webview_wkwebview

dependencies:
  flutter:
    sdk: flutter
  whatfix_flutter_webview_android:
    path: ../whatfix_flutter_webview_android
  whatfix_flutter_webview_platform_interface:
    path: ../whatfix_flutter_webview_platform_interface
  whatfix_flutter_webview_wkwebview:
    path: ../whatfix_flutter_webview_wkwebview

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
